using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Npgsql;

namespace MedSys.Orm
{
    public class Repository<T> where T : new()
    {
        private readonly DbSession _session;
        private readonly EntityMeta _meta;

        public Repository(DbSession session)
        {
            _session = session;
            _meta = EntityMeta.From<T>();
        }

        private static string Q(string ident) => PgTypeMapper.Quote(ident);

        /// <summary>
        /// INSERT u tablicu, vraća novi ID i upisuje ga nazad u entitet.
        /// Pretpostavka: INT PK s AutoGenerated = true.
        /// </summary>
        public async Task<int> InsertAsync(T entity)
        {
            await _session.OpenAsync();

            // Svi stupci koji NISU auto-generated PK
            var cols = _meta.Columns
                .Where(c => !c.IsKey || (c.KeyAttr != null && !c.KeyAttr.AutoGenerated))
                .ToList();

            var colNames = string.Join(", ", cols.Select(c => Q(c.Name)));
            var paramNames = string.Join(", ", cols.Select(c => "@" + c.Name));

            var keyCol = _meta.Key
                        ?? throw new InvalidOperationException($"Entitet {_meta.ClrType.Name} nema ključ.");

            var sql = $"INSERT INTO {Q(_meta.TableName)} ({colNames}) " +
                      $"VALUES ({paramNames}) " +
                      $"RETURNING {Q(keyCol.Name)};";

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            foreach (var c in cols)
            {
                var value = c.Prop.GetValue(entity);

                var clrType = Nullable.GetUnderlyingType(c.ClrType) ?? c.ClrType;
                if (clrType.IsEnum && value != null)
                {
                    value = value.ToString();
                }

                cmd.Parameters.AddWithValue(c.Name, value ?? DBNull.Value);
            }

            var result = await cmd.ExecuteScalarAsync();
            if (result == null)
                throw new InvalidOperationException("InsertAsync nije vratio ID.");

            var newId = Convert.ToInt32(result);
            keyCol.Prop.SetValue(entity, newId);

            return newId;
        }

        /// <summary>
        /// Dohvat entiteta po primarnom ključu.
        /// </summary>
        public async Task<T?> FindAsync(object key)
        {
            await _session.OpenAsync();

            var keyCol = _meta.Key
                        ?? throw new InvalidOperationException($"Entitet {_meta.ClrType.Name} nema ključ.");

            var sql = $"SELECT * FROM {Q(_meta.TableName)} WHERE {Q(keyCol.Name)} = @id;";

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            cmd.Parameters.AddWithValue("id", key);

            await using var reader = await cmd.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return default;

            return MapEntity(reader);
        }

        /// <summary>
        /// Dohvat svih redova iz tablice (bez filtera).
        /// </summary>
        public async Task<List<T>> GetAllAsync()
        {
            await _session.OpenAsync();

            var sql = $"SELECT * FROM {Q(_meta.TableName)};";

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            var list = new List<T>();

            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                list.Add(MapEntity(reader));
            }

            return list;
        }

        public async Task<int> UpdateAsync(T entity)
        {
            await _session.OpenAsync();

            var keyCol = _meta.Key
                        ?? throw new InvalidOperationException($"Entitet {_meta.ClrType.Name} nema ključ.");

            var keyValue = keyCol.Prop.GetValue(entity)
                           ?? throw new InvalidOperationException("Vrijednost ključa ne može biti null.");

            var cols = _meta.Columns
                .Where(c => !c.IsKey)
                .ToList();

            var setClauses = string.Join(", ", cols.Select(c => $"{Q(c.Name)} = @{c.Name}"));

            var sql = $"UPDATE {Q(_meta.TableName)} SET {setClauses} " +
                      $"WHERE {Q(keyCol.Name)} = @key;";

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            foreach (var c in cols)
            {
                var value = c.Prop.GetValue(entity);

                var clrType = Nullable.GetUnderlyingType(c.ClrType) ?? c.ClrType;
                if (clrType.IsEnum && value != null)
                {
                    value = value.ToString();
                }

                cmd.Parameters.AddWithValue(c.Name, value ?? DBNull.Value);
            }

            cmd.Parameters.AddWithValue("key", keyValue);

            return await cmd.ExecuteNonQueryAsync();
        }

        public async Task<int> DeleteAsync(object id)
        {
            await _session.OpenAsync();

            var keyCol = _meta.Key
                        ?? throw new InvalidOperationException($"Entitet {_meta.ClrType.Name} nema ključ.");

            var sql = $"DELETE FROM {Q(_meta.TableName)} WHERE {Q(keyCol.Name)} = @id;";

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            cmd.Parameters.AddWithValue("id", id);

            return await cmd.ExecuteNonQueryAsync();
        }

        public async Task<List<T>> QueryAsync(Action<QueryBuilder>? config = null)
        {
            await _session.OpenAsync();

            var qb = new QueryBuilder(Q(_meta.TableName)); // tablica već quoted
            config?.Invoke(qb);
            var sql = qb.BuildSelect();

            await using var cmd = new NpgsqlCommand(sql, _session.Connection);
            if (_session.Transaction != null)
                cmd.Transaction = _session.Transaction;

            var list = new List<T>();

            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                list.Add(MapEntity(reader));
            }

            return list;
        }
        
        private T MapEntity(NpgsqlDataReader reader)
        {
            var entity = new T();

            foreach (var c in _meta.Columns)
            {
                var ordinal = reader.GetOrdinal(c.Name);

                if (reader.IsDBNull(ordinal))
                {
                    c.Prop.SetValue(entity, null);
                    continue;
                }

                var propType = c.Prop.PropertyType;
                var underlying = Nullable.GetUnderlyingType(propType) ?? propType;

                object value = reader.GetValue(ordinal);

                if (underlying.IsEnum)
                {
                    var s = Convert.ToString(value)!;
                    value = Enum.Parse(underlying, s);
                }
                else
                {
                    value = Convert.ChangeType(value, underlying);
                }

                c.Prop.SetValue(entity, value);
            }

            return entity;
        }
    }
}
