
namespace MedSys.Orm;


[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public sealed class TableAttribute : Attribute
{
    public string Name { get; }
    public TableAttribute(string name) => Name = name;
}

[AttributeUsage(AttributeTargets.Property, Inherited = true)]
public sealed class KeyAttribute : Attribute
{
    public bool AutoGenerated { get; }
    public KeyAttribute(bool autoGenerated = true) => AutoGenerated = autoGenerated;
}

[AttributeUsage(AttributeTargets.Property, Inherited = true)]
public sealed class ColumnAttribute : Attribute
{
    private int length;

    public string? Name { get; set; }
    public string? TypeName { get; set; }
    public int Length { get; set; }
    public bool Nullable { get; set; } = true;
    public string? DefaultSql { get; set; }
    public bool Unique { get; set; } = false;
}

[AttributeUsage(AttributeTargets.Property, Inherited = true)]
public sealed class ForeignKeyAttribute : Attribute
{
    public string RefTable { get; }
    public string RefColumn { get; }
    public ForeignKeyAttribute(string refTable, string refColumn)
    {
        RefTable = refTable;
        RefColumn = refColumn;
    }
}
